package com.example.warteliste;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class KindBearbeiten2 extends VerticalLayout {
	protected TextField name;
	protected TextField surname;
	protected DateField birthday;
	protected ComboBox gender;
	protected TextField phone;
	protected TextField month;
	protected TextField year;
	protected ComboBox hours;
	protected ComboBox weekdays;
	protected TextField parents;
	protected TextField mail;
	protected TextField street;
	protected TextField housenumber;
	protected TextField postcode;
	protected TextField city;
	protected ComboBox acceptChild;

	public KindBearbeiten2() {
		Design.read(this);
	}
}
